apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: {{ .Release.Name }}
spec:
  ingressClassName: public
  rules:
  - host: {{ .Release.Name }}.{{ .Values.captain_domain }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Release.Name }}
            port:
              number: 80
        path: /
        pathType: Prefix