name: Publish the QR-Code_Generator as a ghcr image
 
on: [push]

jobs:
  build_tag_push_to_ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Publish the QR-Code_Generator as a ghcr image
        uses: GlueOps/github-actions-build-push-containers@v0.1.1